status = error
name = PropertiesConfig
packages = org.folio.spring.logging

filters = threshold

filter.threshold.type = ThresholdFilter
filter.threshold.level = debug

appenders = console

appender.console.type = Console
appender.console.name = STDOUT

appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d{HH:mm:ss} [$${folio:requestid}] [$${folio:tenantid}] [$${folio:userid}] [$${folio:moduleid}] %-5p %-20.20C{1} %m%n

rootLogger.level = info
rootLogger.appenderRefs = info
rootLogger.appenderRef.stdout.ref = STDOUT

loggers = folio-ctx-manager, loadable-role-processor, loadable-role-service, loadable-role-helper
logger.folio-ctx-manager.name = org.folio.spring.scope.FolioExecutionScopeExecutionContextManager
logger.folio-ctx-manager.level = error

logger.loadable-role-processor.name = org.folio.roles.service.loadablerole.LoadableRoleCapabilityAssignmentProcessor
logger.loadable-role-processor.level = debug

logger.loadable-role-service.name = org.folio.roles.service.loadablerole.LoadableRoleService
logger.loadable-role-service.level = debug

logger.loadable-role-helper.name = org.folio.roles.service.loadablerole.LoadableRoleCapabilityAssignmentHelper
logger.loadable-role-helper.level = debug
